module.exports = {
  testEnvironment: 'node',
  collectCoverageFrom: [
    'src/services/tokenService.js',
    'src/services/redisService.js',
    'src/services/auditService.js',
    'src/services/socialAuthVerifiers.js',
    'src/utils/otpGenerator.js',
    'src/validators/authValidators.js',
    'src/middleware/rateLimiter.js',
    'src/middleware/validate.js',
    'src/controllers/authController.js',
    'src/services/ledgerService.js',
    'src/services/walletService.js',
    'src/services/marketingCreditService.js',
    'src/notifications/notificationEngine.js',
    'src/notifications/templateEngine.js',
    'src/middleware/permissionMiddleware.js',
    'src/services/adminAuditService.js',
    'src/chat/policy/policyEngine.js',
    'src/chat/policy/detectorRegistry.js',
    'src/chat/chatService.js',
  ],
  coverageDirectory: 'coverage',
  verbose: true,
};
